### PR TITLE
Allow alphanumeric characters in SQLLite style parameters.

### PR DESCRIPTION
**Pull request by BlurrechDev**
- I've made "$" a valid identifier in get_ident_named_placeholder_token().
- Added some tests mixing indexed and named parameters.
- Adjusting the parameter precedence based on the initial QueryParams provided. (Named vs Indexed).
- The first commit https://github.com/shssoichiro/sqlformat-rs/commit/766c92316d77ba18f66c65b57b52838fadf67d03 was sufficient to get to where I wanted to get, the rest just addresses mixed parameter types which might not actually be a real issue anyway...

Attempts to fix https://github.com/shssoichiro/sqlformat-rs/issues/18

I don't have a Rust background so there may be better ways of doing this. 

Happy to adjust as necessary or throw out the lot as it may be.

Thanks.

### CODE REVIEW

**Comment by shssoichiro** [comment]
The code looks fine. Would you be able to run `cargo fmt` and push up the changes?

**Comment by BlurrechDev** [comment]
@shssoichiro Sorted. I had to rejig the token ordering so this would play nicely with the very recent $$ change.

**Comment by max-sixty** [comment]
Thanks for these @BlurrechDev 

@shssoichiro if you'd be up for doing a release, I'd love to integrate this into PRQL

**Comment by shssoichiro** [comment]
Published, thanks!

**Pull request merged**
